Repository Team-Maple/MLS-iOS, pull requests merged in 2025-04, with the labels that each got.

#9 Memory Storage 및 ImageLoader 구현
  MLS/MLS.xcodeproj/project.pbxproj
  MLS/MLSImageLoader/MLSImageLoader/ImageLoader.swift
  MLS/MLSImageLoader/MLSImageLoader/Storage/MemoryStorage.swift
Labels: feat

#11 접근제어자 수정 및 레퍼런스 파일 제거
  MLS/.DS_Store
  MLS/MLS.xcodeproj/project.pbxproj
  MLS/MLSImageLoader/MLSImageLoader/ImageLoader.swift
Labels: fix

#13 ignore 수정
  .gitignore
Labels: chore

#15 readMe 컨벤션 추가
  README.md
Labels: docs

#17 DiskStorage 구현
  MLS/MLSImageLoader/MLSImageLoader/ImageLoader.swift
  MLS/MLSImageLoader/MLSImageLoader/Storage/DiskStorage.swift
Labels: feat

#18 image loader개발
  .DS_Store
  MLS/.DS_Store
  MLS/MLS.xcodeproj/project.pbxproj
  MLS/MLS/.DS_Store
  MLS/MLS/Application/AppDelegate.swift
  MLS/MLS/Application/SceneDelegate.swift
  MLS/MLS/Application/ViewController.swift
  MLS/MLS/Base.lproj/Main.storyboard
  MLS/MLS/Resource/Assets.xcassets/AccentColor.colorset/Contents.json
  MLS/MLS/Resource/Assets.xcassets/AppIcon.appiconset/Contents.json
  MLS/MLS/Resource/Assets.xcassets/Contents.json
  MLS/MLS/Resource/Base.lproj/LaunchScreen.storyboard
  MLS/MLS/Resource/Info.plist
  MLS/MLSData/.DS_Store
  MLS/MLSData/MLSData.xcodeproj/project.pbxproj
  MLS/MLSData/MLSData/MLSData.h
  MLS/MLSDomain/.DS_Store
  MLS/MLSDomain/MLSDomain.xcodeproj/project.pbxproj
  MLS/MLSDomain/MLSDomain/MLSDomain.h
  MLS/MLSPresentation/.DS_Store
  MLS/MLSPresentation/MLSPresentation.xcodeproj/project.pbxproj
  MLS/MLSPresentation/MLSPresentation/MLSPresentation.h
  MLS/MLSPresentation/MLSPresentationUtills/.DS_Store
  MLS/MLSPresentation/MLSPresentationUtills/MLSPresentationUtills.xcodeproj/project.pbxproj
  MLS/MLSPresentation/MLSPresentationUtills/MLSPresentationUtills.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  MLS/MLSPresentation/MLSPresentationUtills/MLSPresentationUtills/ImageLoader/ImageLoader.swift
  MLS/MLSPresentation/MLSPresentationUtills/MLSPresentationUtills/ImageLoader/MLSImageLoader.h
  MLS/MLSPresentation/MLSPresentationUtills/MLSPresentationUtills/ImageLoader/Storage/DiskStorage.swift
  MLS/MLSPresentation/MLSPresentationUtills/MLSPresentationUtills/ImageLoader/Storage/MemoryStorage.swift
  MLS/MLSPresentation/MLSPresentationUtills/MLSPresentationUtills/MLSPresentationUtills.h
  MLSData/MLSData/MLSData.h
  MLSDomain/MLSDomain.xcodeproj/project.pbxproj
  MLSDomain/MLSDomain.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  MLSDomain/MLSDomain/MLSDomain.h
  MLSPresentation/MLSPresentation.xcodeproj/project.pbxproj
  MLSPresentation/MLSPresentation.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  MLSPresentation/MLSPresentation/MLSPresentation.h
Labels: feat, chore

#21 lint 추가 및 세팅
  .gitignore
  MLS/.swiftlint.yml
  MLS/MLS.xcodeproj/project.pbxproj
  MLS/MLS.xcodeproj/xcshareddata/xcschemes/MLS.xcscheme
  MLS/MLS/Application/AppDelegate.swift
  MLS/MLS/Application/SceneDelegate.swift
  MLS/MLS/Application/ViewController.swift
  MLS/MLSPresentation/MLSPresentationUtills/MLSPresentationUtills/.DS_Store
  MLS/MLSPresentation/MLSPresentationUtills/MLSPresentationUtills/ImageLoader/ImageLoader.swift
  MLS/MLSPresentation/MLSPresentationUtills/MLSPresentationUtills/ImageLoader/Storage/DiskStorage.swift
  MLS/MLSPresentation/MLSPresentationUtills/MLSPresentationUtills/ImageLoader/Storage/MemoryStorage.swift
Labels: style, add, chore

#23 네트워크 통신 모듈 구현
  .DS_Store
  MLS/.DS_Store
  MLS/.swiftlint.yml
  MLS/MLS.xcodeproj/project.pbxproj
  MLS/MLS.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  MLS/MLSData/MLSData.xcodeproj/project.pbxproj
  MLS/MLSData/MLSData/Network/EndPoint/EndPoint.swift
  MLS/MLSData/MLSData/Network/EndPoint/Interface/Entity/NetworkLayer.swift
  MLS/MLSData/MLSData/Network/EndPoint/Interface/Requestable.swift
  MLS/MLSData/MLSData/Network/EndPoint/Interface/Responsable.swift
  MLS/MLSData/MLSData/Network/EndPoint/ResponsableEndPoint.swift
  MLS/MLSData/MLSData/Network/Interceptor/RequestInterceptor.swift
  MLS/MLSData/MLSData/Network/Interface/Interceptor.swift
  MLS/MLSData/MLSData/Network/Interface/Provider.swift
  MLS/MLSData/MLSData/Network/Provider/ProviderImpl.swift
Labels: feat

#28 네트워크 통신 모듈 테스트
  MLS/Data/Data/Network/Provider/ProviderImpl.swift
  MLS/DomainInterface/DomainInterface/Interface/Network/Requestable.swift
  MLS/MLS.xcodeproj/project.pbxproj
  MLS/MLS.xcodeproj/xcshareddata/xcschemes/MLSTests.xcscheme
  MLS/MLS.xcworkspace/xcshareddata/swiftpm/Package.resolved
  MLS/MLSTests/MLSTests.swift
  MLS/MLSTests/ProviderTests.swift
Labels: fix, test

#29 build test 추가
  MLS/MLSTests/MLSTests.swift
Labels: test
