Repository Team-Maple/MLS-iOS, pull requests merged in 2025-06, with the labels that each got.

#91 interceptor 구현
  MLS/Data/Data/Errors/NetworkError.swift
  MLS/Data/Data/Providers/NetworkProviderImpl.swift
  MLS/Domain/Domain/Interceptor/TokenInterceptor.swift
  MLS/Domain/DomainInterface/Interface/Network/Interceptor.swift
Labels: feat

#109 CheckBoxButton 수정
  MLS/Presentation/AuthFeature/AuthFeature/TermsAgreement/TermsAgreementView.swift
  MLS/Presentation/DesignSystem/DesignSystem/Components/CheckBoxButton.swift
  MLS/Presentation/DesignSystem/DesignSystemDemo/ComponentsTest/CheckBoxButtonTestViewController.swift
Labels: fix

#114 Header
  MLS/Presentation/DesignSystem/DesignSystem/Components/Header.swift
  MLS/Presentation/DesignSystem/DesignSystem/Resource/Image.xcassets/bell.imageset/Contents.json
  MLS/Presentation/DesignSystem/DesignSystem/Resource/Image.xcassets/bell.imageset/bell.svg
  MLS/Presentation/DesignSystem/DesignSystem/Resource/Image.xcassets/markX.imageset/Contents.json
  MLS/Presentation/DesignSystem/DesignSystem/Resource/Image.xcassets/markX.imageset/x-black_big.svg
  MLS/Presentation/DesignSystem/DesignSystem/Resource/Image.xcassets/search.imageset/Contents.json
  MLS/Presentation/DesignSystem/DesignSystem/Resource/Image.xcassets/search.imageset/seach.svg
  MLS/Presentation/DesignSystem/DesignSystemDemo/ComponentsTest/HeaderTestViewController.swift
  MLS/Presentation/DesignSystem/DesignSystemDemo/ViewController.swift
Labels: feat

#115 Header
  MLS/Presentation/DesignSystem/DesignSystem/Components/Header.swift
Labels: fix

#117 TagChip
  MLS/Presentation/DesignSystem/DesignSystem/Components/Header.swift
  MLS/Presentation/DesignSystem/DesignSystem/Components/TagChip.swift
  MLS/Presentation/DesignSystem/DesignSystem/Components/TapButton.swift
  MLS/Presentation/DesignSystem/DesignSystem/Resource/Image.xcassets/largeX.imageset/Contents.json
  MLS/Presentation/DesignSystem/DesignSystem/Resource/Image.xcassets/largeX.imageset/x-black_big.svg
  MLS/Presentation/DesignSystem/DesignSystem/Resource/Image.xcassets/smallX.imageset/Contents.json
  MLS/Presentation/DesignSystem/DesignSystem/Resource/Image.xcassets/smallX.imageset/x-black.svg
  MLS/Presentation/DesignSystem/DesignSystem/Utills/Extension/UIImage+.swift
  MLS/Presentation/DesignSystem/DesignSystemDemo/ComponentsTest/TagChipTestViewController.swift
  MLS/Presentation/DesignSystem/DesignSystemDemo/ViewController.swift
Labels: feat

#119 GuideAlert
  MLS/Presentation/AuthFeature/AuthFeature/OnBoarding/Notification/Modal/OnBoardingModalView.swift
  MLS/Presentation/AuthFeature/AuthFeature/OnBoarding/OnBoardingBaseView.swift
  MLS/Presentation/BaseFeature/BaseFeature/Utills/ModalPresentable/ModalPresentable.swift
  MLS/Presentation/BaseFeature/BaseFeature/Utills/ModalPresentable/ModalWrapperView.swift
  MLS/Presentation/DesignSystem/DesignSystem/Components/CommonButton.swift
  MLS/Presentation/DesignSystem/DesignSystem/Components/GuideAlert.swift
  MLS/Presentation/DesignSystem/DesignSystem/Resource/Image.xcassets/warning.imageset/Contents.json
  MLS/Presentation/DesignSystem/DesignSystem/Resource/Image.xcassets/warning.imageset/warning.svg
  MLS/Presentation/DesignSystem/DesignSystemDemo/ComponentsTest/GuideAlert/GuideAlertTestViewController.swift
  MLS/Presentation/DesignSystem/DesignSystemDemo/ComponentsTest/GuideAlert/OneButtonGuideAlert.swift
  MLS/Presentation/DesignSystem/DesignSystemDemo/ComponentsTest/GuideAlert/TwoButtonGuideAlert.swift
  MLS/Presentation/DesignSystem/DesignSystemDemo/ViewController.swift
Labels: feat, fix

#127 dictionary feature 추가
  MLS/MLS.xcworkspace/contents.xcworkspacedata
  MLS/Presentation/DictionaryFeature/DictionaryFeature.xcodeproj/project.pbxproj
  MLS/Presentation/DictionaryFeature/DictionaryFeature.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  MLS/Presentation/DictionaryFeature/DictionaryFeature/TempFile.swift
Labels: add

#128 dictionary feature
  MLS/Data/Data.xcodeproj/project.pbxproj
  MLS/Presentation/AuthFeature/AuthFeature.xcodeproj/project.pbxproj
  MLS/Presentation/DictionaryFeature/DictionaryFeature.xcodeproj/project.pbxproj
  MLS/Presentation/DictionaryFeature/DictionaryFeatureDemo/AppDelegate.swift
  MLS/Presentation/DictionaryFeature/DictionaryFeatureDemo/Assets.xcassets/AccentColor.colorset/Contents.json
  MLS/Presentation/DictionaryFeature/DictionaryFeatureDemo/Assets.xcassets/AppIcon.appiconset/Contents.json
  MLS/Presentation/DictionaryFeature/DictionaryFeatureDemo/Assets.xcassets/Contents.json
  MLS/Presentation/DictionaryFeature/DictionaryFeatureDemo/Base.lproj/LaunchScreen.storyboard
  MLS/Presentation/DictionaryFeature/DictionaryFeatureDemo/Base.lproj/Main.storyboard
  MLS/Presentation/DictionaryFeature/DictionaryFeatureDemo/Info.plist
  MLS/Presentation/DictionaryFeature/DictionaryFeatureDemo/SceneDelegate.swift
  MLS/Presentation/DictionaryFeature/DictionaryFeatureDemo/ViewController.swift
  MLS/Presentation/DictionaryFeature/DictionaryFeatureInterface/TempFile.swift
Labels: add, chore

#133 itemfilter UI, Compositional Layout builder
  MLS/Presentation/BaseFeature/BaseFeature/UICollectionReusableViews/CollectionViewCells/PageTabbarCell.swift
  MLS/Presentation/BaseFeature/BaseFeature/UICollectionReusableViews/CollectionViewCells/TapButtonCell.swift
  MLS/Presentation/BaseFeature/BaseFeature/UICollectionReusableViews/Views/PageTabbarDividerView.swift
  MLS/Presentation/BaseFeature/BaseFeature/UICollectionReusableViews/Views/SubTitleBoldHeaderView.swift
  MLS/Presentation/BaseFeature/BaseFeature/Utills/CompositionalLayoutBuilder/CompositionalLayoutBuilder.swift
  MLS/Presentation/BaseFeature/BaseFeature/Utills/CompositionalLayoutBuilder/CompositionalSectionBuilder.swift
  MLS/Presentation/BaseFeature/BaseFeature/Utills/CompositionalLayoutBuilder/LayoutFactory.swift
  MLS/Presentation/BaseFeature/BaseFeature/Utills/Extension/UICollectionReusableView+.swift
  MLS/Presentation/BaseFeature/BaseFeature/Utills/ModalPresentable/ModalPresentable.swift
  MLS/Presentation/BaseFeature/BaseFeature/Utills/ModalPresentable/ModalWrapperView.swift
  MLS/Presentation/BaseFeature/BaseFeature/Utills/ModalPresentable/UIViewController+.swift
  MLS/Presentation/DesignSystem/DesignSystem/Components/CheckBoxButton.swift
  MLS/Presentation/DesignSystem/DesignSystem/Components/CommonButton.swift
  MLS/Presentation/DesignSystem/DesignSystem/Components/Header.swift
  MLS/Presentation/DesignSystem/DesignSystem/Components/TapButton.swift
  MLS/Presentation/DesignSystem/DesignSystem/Utills/Extension/UIColor+.swift
  MLS/Presentation/DictionaryFeature/DictionaryFeature.xcodeproj/project.pbxproj
  MLS/Presentation/DictionaryFeature/DictionaryFeature/ItemFilterBottomSheet/ItemFilterBottomSheetView.swift
  MLS/Presentation/DictionaryFeature/DictionaryFeature/ItemFilterBottomSheet/ItemFilterBottomSheetViewController.swift
  MLS/Presentation/DictionaryFeature/DictionaryFeature/ItemFilterBottomSheet/ItemFilterBottomSheetViewReactor.swift
  MLS/Presentation/DictionaryFeature/DictionaryFeature/TempFile.swift
  MLS/Presentation/DictionaryFeature/DictionaryFeatureDemo/AppDelegate.swift
  MLS/Presentation/DictionaryFeature/DictionaryFeatureDemo/Base.lproj/Main.storyboard
  MLS/Presentation/DictionaryFeature/DictionaryFeatureDemo/Info.plist
  MLS/Presentation/DictionaryFeature/DictionaryFeatureDemo/SceneDelegate.swift
  MLS/Presentation/DictionaryFeature/DictionaryFeatureDemo/ViewController.swift
Labels: feat

#139 Dictionarry MainList + Search UI 구현
  MLS/.DS_Store
  MLS/Data/DataMock/Repository/DictionaryListRepositoryImpl.swift
  MLS/Domain/Domain/UseCaseImpl/DictionaryList/FetchDictionaryItemsUseCaseImpl.swift
  MLS/Domain/Domain/UseCaseImpl/DictionaryList/ToggleBookmarkUseCaseImpl.swift
  MLS/Domain/DomainInterface/Entity/DictionaryList/DictionaryItem.swift
  MLS/Domain/DomainInterface/Entity/DictionaryList/DictionaryType.swift
  MLS/Domain/DomainInterface/Entity/DictionaryList/DictionnaryItemType.swift
  MLS/Domain/DomainInterface/Repository/DictionaryListRepository.swift
  MLS/Domain/DomainInterface/UseCase/DictionaryList/FetchDictionaryItemUseCase.swift
  MLS/Domain/DomainInterface/UseCase/DictionaryList/ToggleBookmarkUseCase.swift
  MLS/Presentation/BaseFeature/BaseFeature/UICollectionReusableViews/Views/PopularSearchHeaderView.swift
  MLS/Presentation/BaseFeature/BaseFeature/UICollectionReusableViews/Views/RecentSearchHeaderView.swift
  MLS/Presentation/BaseFeature/BaseFeature/UICollectionReusableViews/Views/SearchDividerView.swift
  MLS/Presentation/BaseFeature/BaseFeature/Utills/CompositionalLayoutBuilder/LayoutFactory.swift
  MLS/Presentation/BaseFeature/BaseFeature/Utills/GuideAlertFactory.swift
  MLS/Presentation/BaseFeature/BaseFeature/Utills/ImageLoader/ImageLoader.swift
  MLS/Presentation/DesignSystem/DesignSystem/Components/CardList.swift
  MLS/Presentation/DesignSystem/DesignSystem/Components/GuideAlert.swift
  MLS/Presentation/DesignSystem/DesignSystem/Components/Header.swift
  MLS/Presentation/DesignSystem/DesignSystem/Components/Tabbar/BottomTabBar.swift
  MLS/Presentation/DesignSystem/DesignSystem/Components/Tabbar/BottomTabBarController.swift
  MLS/Presentation/DesignSystem/DesignSystem/Components/Tabbar/TabButton.swift
  MLS/Presentation/DesignSystem/DesignSystem/Components/TagChip.swift
  MLS/Presentation/DesignSystem/DesignSystem/Resource/Image.xcassets/filter.imageset/Contents.json
  MLS/Presentation/DesignSystem/DesignSystem/Resource/Image.xcassets/filter.imageset/filter.svg
  MLS/Presentation/DesignSystem/DesignSystem/Resource/Image.xcassets/testImage.imageset/Contents.json
  MLS/Presentation/DesignSystem/DesignSystem/Resource/Image.xcassets/testImage.imageset/testImage.png
  MLS/Presentation/DesignSystem/DesignSystemDemo/ComponentsTest/GuideAlert/OneButtonGuideAlert.swift
  MLS/Presentation/DesignSystem/DesignSystemDemo/ComponentsTest/GuideAlert/TwoButtonGuideAlert.swift
  MLS/Presentation/DesignSystem/DesignSystemDemo/ComponentsTest/GuideAlertTestViewController.swift
  MLS/Presentation/DesignSystem/DesignSystemDemo/ComponentsTest/HeaderTestViewController.swift
  MLS/Presentation/DesignSystem/DesignSystemDemo/ViewController.swift
  MLS/Presentation/DictionaryFeature/DictionaryFeature.xcodeproj/project.pbxproj
  MLS/Presentation/DictionaryFeature/DictionaryFeature.xcodeproj/xcshareddata/xcschemes/DictionaryFeatureDemo.xcscheme
  MLS/Presentation/DictionaryFeature/DictionaryFeature/DictionaryMain/DictionaryList/DictionaryListCell.swift
  MLS/Presentation/DictionaryFeature/DictionaryFeature/DictionaryMain/DictionaryList/DictionaryListFactoryImpl.swift
  MLS/Presentation/DictionaryFeature/DictionaryFeature/DictionaryMain/DictionaryList/DictionaryListReactor.swift
  MLS/Presentation/DictionaryFeature/DictionaryFeature/DictionaryMain/DictionaryList/DictionaryListView.swift
  MLS/Presentation/DictionaryFeature/DictionaryFeature/DictionaryMain/DictionaryList/DictionaryListViewController.swift
  MLS/Presentation/DictionaryFeature/DictionaryFeature/DictionaryMain/DictionaryMainReactor.swift
  MLS/Presentation/DictionaryFeature/DictionaryFeature/DictionaryMain/DictionaryMainView.swift
  MLS/Presentation/DictionaryFeature/DictionaryFeature/DictionaryMain/DictionaryMainViewController.swift
  MLS/Presentation/DictionaryFeature/DictionaryFeature/DictionaryMain/DictionaryMainViewFactoryImpl.swift
  MLS/Presentation/DictionaryFeature/DictionaryFeature/DictionaryMain/DictionarySearch/DictionarySearchFactoryImpl.swift
  MLS/Presentation/DictionaryFeature/DictionaryFeature/DictionaryMain/DictionarySearch/DictionarySearchReactor.swift
  MLS/Presentation/DictionaryFeature/DictionaryFeature/DictionaryMain/DictionarySearch/DictionarySearchView.swift
  MLS/Presentation/DictionaryFeature/DictionaryFeature/DictionaryMain/DictionarySearch/DictionarySearchViewController.swift
  MLS/Presentation/DictionaryFeature/DictionaryFeature/DictionaryMain/DictionarySearch/PopularResultCell.swift
  MLS/Presentation/DictionaryFeature/DictionaryFeature/DictionaryMain/DictionarySearch/TagChipCell.swift
  MLS/Presentation/DictionaryFeature/DictionaryFeature/ItemFilterBottomSheet/ItemFilterBottomSheetViewController.swift
  MLS/Presentation/DictionaryFeature/DictionaryFeature/ItemFilterBottomSheet/Views/ItemFilterBottomSheetView.swift
  MLS/Presentation/DictionaryFeature/DictionaryFeatureDemo/AppDelegate.swift
  MLS/Presentation/DictionaryFeature/DictionaryFeatureDemo/SceneDelegate.swift
  MLS/Presentation/DictionaryFeature/DictionaryFeatureDemo/ViewController.swift
  MLS/Presentation/DictionaryFeature/DictionaryFeatureInterface/DictionaryListFactory.swift
  MLS/Presentation/DictionaryFeature/DictionaryFeatureInterface/DictionaryMainViewFactory.swift
  MLS/Presentation/DictionaryFeature/DictionaryFeatureInterface/DictionarySearchFactory.swift
  MLS/Presentation/DictionaryFeature/DictionaryFeatureInterface/TempFile.swift
Labels: feat, fix, refactor

#143 도감 검색 UI
  MLS/Presentation/BaseFeature/BaseFeature/Base/BaseViewController.swift
  MLS/Presentation/DictionaryFeature/DictionaryFeature/DictionaryMain/DictionaryList/DictionaryListFactoryImpl.swift
  MLS/Presentation/DictionaryFeature/DictionaryFeature/DictionaryMain/DictionaryList/DictionaryListView.swift
  MLS/Presentation/DictionaryFeature/DictionaryFeature/DictionaryMain/DictionaryMainReactor.swift
  MLS/Presentation/DictionaryFeature/DictionaryFeature/DictionaryMain/DictionaryMainView.swift
  MLS/Presentation/DictionaryFeature/DictionaryFeature/DictionaryMain/DictionaryMainViewController.swift
  MLS/Presentation/DictionaryFeature/DictionaryFeature/DictionaryMain/DictionaryMainViewFactoryImpl.swift
  MLS/Presentation/DictionaryFeature/DictionaryFeature/DictionaryMain/DictionarySearch/DictionarySearchFactoryImpl.swift
  MLS/Presentation/DictionaryFeature/DictionaryFeature/DictionaryMain/DictionarySearch/DictionarySearchReactor.swift
  MLS/Presentation/DictionaryFeature/DictionaryFeature/DictionaryMain/DictionarySearch/DictionarySearchViewController.swift
  MLS/Presentation/DictionaryFeature/DictionaryFeature/DictionaryMain/DictionarySearch/SearchResult/DictionarySearchResultFactoryImpl.swift
  MLS/Presentation/DictionaryFeature/DictionaryFeature/DictionaryMain/DictionarySearch/SearchResult/DictionarySearchResultReactor.swift
  MLS/Presentation/DictionaryFeature/DictionaryFeature/DictionaryMain/DictionarySearch/SearchResult/DictionarySearchResultViewController.swift
  MLS/Presentation/DictionaryFeature/DictionaryFeatureDemo/AppDelegate.swift
  MLS/Presentation/DictionaryFeature/DictionaryFeatureInterface/DictionaryListFactory.swift
  MLS/Presentation/DictionaryFeature/DictionaryFeatureInterface/DictionaryMainListFactory.swift
  MLS/Presentation/DictionaryFeature/DictionaryFeatureInterface/DictionarySearchResultFactory.swift
Labels: feat

#154 custom modal 버그 수정
  MLS/Presentation/BaseFeature/BaseFeature/Utills/ModalPresentable/UIViewController+.swift
  MLS/Presentation/DictionaryFeature/DictionaryFeature.xcodeproj/project.pbxproj
  MLS/Presentation/DictionaryFeature/DictionaryFeature/DictionaryMain/DictionaryList/DictionaryListViewController.swift
  MLS/Presentation/DictionaryFeature/DictionaryFeatureDemo/AppDelegate.swift
Labels: fix, chore

#155 FloatingActionButton
  MLS/Presentation/BaseFeature/BaseFeature/Utills/ModalPresentable/UIViewController+.swift
  MLS/Presentation/DesignSystem/DesignSystem/Components/FloatingActionButton.swift
  MLS/Presentation/DesignSystem/DesignSystem/Resource/Image.xcassets/plus.imageset/Contents.json
  MLS/Presentation/DesignSystem/DesignSystem/Resource/Image.xcassets/plus.imageset/plus.svg
  MLS/Presentation/DictionaryFeature/DictionaryFeature/DictionaryMain/DictionarySearch/DictionarySearchReactor.swift
Labels: feat

#156 CollectionList
  MLS/Presentation/DesignSystem/DesignSystem/Components/CollectionList.swift
  MLS/Presentation/DesignSystem/DesignSystem/Resource/Image.xcassets/arrowRightBold.imageset/Contents.json
  MLS/Presentation/DesignSystem/DesignSystem/Resource/Image.xcassets/arrowRightBold.imageset/arrowRightBold.svg
  MLS/Presentation/DesignSystem/DesignSystem/Utills/NSAttributedString.swift
  MLS/Presentation/DesignSystem/DesignSystemDemo/ComponentsTest/CollectionListTestViewController.swift
  MLS/Presentation/DesignSystem/DesignSystemDemo/ViewController.swift
Labels: feat

#157 SnackBar 구현
  MLS/Presentation/BaseFeature/BaseFeature/Utills/SnackBarFactory.swift
  MLS/Presentation/DesignSystem/DesignSystem/Components/CardList.swift
  MLS/Presentation/DesignSystem/DesignSystem/Components/CollectionList.swift
  MLS/Presentation/DesignSystem/DesignSystem/Components/CommonButton.swift
  MLS/Presentation/DesignSystem/DesignSystem/Components/ItemImageView.swift
  MLS/Presentation/DesignSystem/DesignSystem/Components/SnackBar.swift
  MLS/Presentation/DesignSystem/DesignSystem/Components/Tabbar/TabButton.swift
  MLS/Presentation/DesignSystem/DesignSystem/Resource/Image.xcassets/bookmark.imageset/Contents.json
  MLS/Presentation/DesignSystem/DesignSystem/Resource/Image.xcassets/bookmark.imageset/bookmark_false.svg
  MLS/Presentation/DesignSystem/DesignSystem/Resource/Image.xcassets/bookmark.imageset/bookmark_true.svg
  MLS/Presentation/DesignSystem/DesignSystem/Resource/Image.xcassets/bookmark_fill.imageset/Contents.json
  MLS/Presentation/DesignSystem/DesignSystem/Resource/Image.xcassets/bookmark_fill.imageset/bookmark_fill.svg
  MLS/Presentation/DesignSystem/DesignSystem/Resource/Image.xcassets/dictionary.imageset/Contents.json
  MLS/Presentation/DesignSystem/DesignSystem/Resource/Image.xcassets/dictionary.imageset/dictionary_false.svg
  MLS/Presentation/DesignSystem/DesignSystem/Resource/Image.xcassets/dictionary.imageset/dictionary_true.svg
  MLS/Presentation/DesignSystem/DesignSystem/Resource/Image.xcassets/favorite.imageset/Contents.json
  MLS/Presentation/DesignSystem/DesignSystem/Resource/Image.xcassets/favorite.imageset/favorite_false.svg
  MLS/Presentation/DesignSystem/DesignSystem/Resource/Image.xcassets/favorite.imageset/favorite_true.svg
  MLS/Presentation/DesignSystem/DesignSystem/Resource/Image.xcassets/mypage.imageset/Contents.json
  MLS/Presentation/DesignSystem/DesignSystem/Resource/Image.xcassets/mypage.imageset/mypage_false.svg
  MLS/Presentation/DesignSystem/DesignSystem/Resource/Image.xcassets/mypage.imageset/mypage_true.svg
  MLS/Presentation/DesignSystem/DesignSystemDemo/ComponentsTest/CardListTestViewController.swift
  MLS/Presentation/DesignSystem/DesignSystemDemo/ComponentsTest/CommonButtonTestViewController.swift
  MLS/Presentation/DesignSystem/DesignSystemDemo/ComponentsTest/SnackBarTestViewController.swift
  MLS/Presentation/DesignSystem/DesignSystemDemo/ViewController.swift
  MLS/Presentation/DictionaryFeature/DictionaryFeature/DictionaryMain/DictionaryList/DictionaryListCell.swift
Labels: feat
