Repository Team-Maple/MLS-iOS, pull requests merged in 2025-05, with the labels that each got.

#34 DIContainer 구현 및 테스트
  MLS/Core/Core.xcodeproj/project.pbxproj
  MLS/Core/Core/DIContainer/DIContainer.swift
  MLS/Core/Core/Temp.swift
  MLS/Core/DIContainerTests/DIContainerTests.swift
  MLS/MLS/Application/ViewController.swift
Labels: feat, test

#38 apple login 모듈 개발 및 인터페이스 개발
  MLS/Data/Data/Errors/AuthError.swift
  MLS/Data/Data/Errors/NetworkError.swift
  MLS/Data/Data/Network/.DS_Store
  MLS/Data/Data/Network/Endpoints/EndPoint.swift
  MLS/Data/Data/Network/Endpoints/ResponsableEndPoint.swift
  MLS/Data/Data/Network/Interceptor/RequestInterceptor.swift
  MLS/Data/Data/Providers/AppleLoginProviderImpl.swift
  MLS/Data/Data/Providers/NetworkProviderImpl.swift
  MLS/DomainInterface/DomainInterface/Interface/Network/HTTPMethod.swift
  MLS/DomainInterface/DomainInterface/Interface/SocialAuthenticatable/SocialAuthenticatable.swift
  MLS/DomainInterface/DomainInterface/Providers/NetworkProvider.swift
  MLS/DomainInterface/DomainInterface/Providers/SocialAuthenticatableProvider.swift
  MLS/DomainInterface/DomainInterface/UseCase/SocialLoginUseCase.swift
  MLS/MLSTests/ProviderTests.swift
Labels: feat

#39 social login 구현
  MLS/.DS_Store
  MLS/Core/Core.h
  MLS/Core/Core.xcodeproj/project.pbxproj
  MLS/Data/Data.h
  MLS/Data/Data.xcodeproj/project.pbxproj
  MLS/Data/Data/Errors/AuthError.swift
  MLS/Data/Data/Errors/NetworkError.swift
  MLS/Data/Data/Network/.DS_Store
  MLS/Data/Data/Network/Endpoints/EndPoint.swift
  MLS/Data/Data/Network/Endpoints/ResponsableEndPoint.swift
  MLS/Data/Data/Network/Interceptor/RequestInterceptor.swift
  MLS/Data/Data/Providers/AppleLoginProviderImpl.swift
  MLS/Data/Data/Providers/NetworkProviderImpl.swift
  MLS/Domain/.DS_Store
  MLS/Domain/Domain.h
  MLS/Domain/Domain.xcodeproj/project.pbxproj
  MLS/Domain/DomainInterface/Interface/.DS_Store
  MLS/Domain/DomainInterface/Interface/Network/HTTPMethod.swift
  MLS/Domain/DomainInterface/Interface/Network/Interceptor.swift
  MLS/Domain/DomainInterface/Interface/Network/Requestable.swift
  MLS/Domain/DomainInterface/Interface/Network/Responsable.swift
  MLS/Domain/DomainInterface/Providers/NetworkProvider.swift
  MLS/Domain/DomainInterface/Providers/SocialAuthenticatableProvider.swift
  MLS/Domain/DomainInterface/UseCase/SocialLoginUseCase.swift
  MLS/DomainInterface/.DS_Store
  MLS/DomainInterface/DomainInterface.xcodeproj/project.pbxproj
  MLS/DomainInterface/DomainInterface/Interface/Network/HTTPMethod.swift
  MLS/DomainInterface/DomainInterface/Providers/NetworkProvider.swift
  MLS/DomainInterface/DomainInterface/Providers/SocialAuthenticatableProvider.swift
  MLS/DomainInterface/DomainInterface/UseCase/SocialLoginUseCase.swift
  MLS/MLS.xcodeproj/project.pbxproj
  MLS/MLS.xcworkspace/contents.xcworkspacedata
  MLS/MLSTests/ProviderTests.swift
  MLS/Presentation/Presentation.h
  MLS/Presentation/Presentation.xcodeproj/project.pbxproj
Labels: feat

#41 conflict solve
  MLS/.DS_Store
  MLS/DomainInterface/.DS_Store
  MLS/DomainInterface/DomainInterface.h
  MLS/DomainInterface/DomainInterface/.DS_Store
  MLS/DomainInterface/DomainInterface/Interface/.DS_Store
  MLS/DomainInterface/DomainInterface/Interface/Network/HTTPMethod.swift
  MLS/DomainInterface/DomainInterface/Interface/Network/Interceptor.swift
  MLS/DomainInterface/DomainInterface/Interface/Network/Requestable.swift
  MLS/DomainInterface/DomainInterface/Interface/Network/Responsable.swift
  MLS/DomainInterface/DomainInterface/Providers/NetworkProvider.swift
  MLS/DomainInterface/DomainInterface/Providers/SocialAuthenticatableProvider.swift
  MLS/DomainInterface/DomainInterface/UseCase/SocialLoginUseCase.swift
Labels: chore

#45 약관동의화면
  MLS/.DS_Store
  MLS/Presentation/DesignSystem/DesignSystem.xcodeproj/project.pbxproj
  MLS/Presentation/DesignSystem/DesignSystem/Components/CheckButton.swift
  MLS/Presentation/DesignSystem/DesignSystem/Components/DividerView.swift
  MLS/Presentation/DesignSystem/DesignSystem/Components/HeaderView.swift
  MLS/Presentation/DesignSystem/DesignSystem/Resource/Image.xcassets/arrowForward.imageset/Property 1=arrowForward.png
  MLS/Presentation/DesignSystem/DesignSystem/Resource/Image.xcassets/arrowLeft.imageset/Contents.json
  MLS/Presentation/DesignSystem/DesignSystem/Resource/Image.xcassets/arrowLeft.imageset/arrowLeft.png
  MLS/Presentation/DesignSystem/DesignSystem/Resource/Image.xcassets/arrowRight.imageset/Contents.json
  MLS/Presentation/DesignSystem/DesignSystem/Resource/Image.xcassets/arrowRight.imageset/arrowRight.png
  MLS/Presentation/DesignSystem/DesignSystem/Utills/FontManager.swift
  MLS/Presentation/DesignSystem/DesignSystemDemo/Application/AppDelegate.swift
  MLS/Presentation/DesignSystem/DesignSystemDemo/Application/SceneDelegate.swift
  MLS/Presentation/DesignSystem/DesignSystemDemo/Base.lproj/Main.storyboard
  MLS/Presentation/DesignSystem/DesignSystemDemo/ComponentsTest/CheckButtonTestViewController.swift
  MLS/Presentation/DesignSystem/DesignSystemDemo/ComponentsTest/HeaderTestViewController.swift
  MLS/Presentation/DesignSystem/DesignSystemDemo/Info.plist
  MLS/Presentation/DesignSystem/DesignSystemDemo/ViewController.swift
Labels: feat

#64 attribute string extension 및 color, font 수정
  MLS/Presentation/DesignSystem/DesignSystem/Components/CheckButton.swift
  MLS/Presentation/DesignSystem/DesignSystem/Components/CommonButton.swift
  MLS/Presentation/DesignSystem/DesignSystem/Components/NavigationBarView.swift
  MLS/Presentation/DesignSystem/DesignSystem/Utills/Extension/UIColor+.swift
  MLS/Presentation/DesignSystem/DesignSystem/Utills/Extension/UIFont+.swift
  MLS/Presentation/DesignSystem/DesignSystem/Utills/NSAttributedString.swift
Labels: feat, fix

#65 check box button 수정
  MLS/Presentation/AuthFeature/AuthFeature/TermsAgreement/TermsAgreementView.swift
  MLS/Presentation/DesignSystem/DesignSystem/Components/CheckBoxButton.swift
  MLS/Presentation/DesignSystem/DesignSystem/Utills/NSAttributedString.swift
  MLS/Presentation/DesignSystem/DesignSystemDemo/ComponentsTest/CheckBoxButtonTestViewController.swift
  MLS/Presentation/DesignSystem/DesignSystemDemo/ViewController.swift
Labels: fix

#68 navigation bar 수정
  MLS/Presentation/AuthFeature/AuthFeature/TermsAgreement/TermsAgreementView.swift
  MLS/Presentation/DesignSystem/DesignSystem/Components/NavigationBar.swift
  MLS/Presentation/DesignSystem/DesignSystemDemo/ComponentsTest/NavigationBarTestViewController.swift
Labels: fix

#71 Toast 개발
  MLS/Presentation/DesignSystem/DesignSystem/Components/Toast.swift
  MLS/Presentation/DesignSystem/DesignSystemDemo/ComponentsTest/ToastMakerTestViewController.swift
  MLS/Presentation/DesignSystem/DesignSystemDemo/ViewController.swift
Labels: feat

#72 약관동의화면 변경사항 적용
  MLS/Presentation/AuthFeature/AuthFeature/TermsAgreement/TermsAgreementView.swift
  MLS/Presentation/DesignSystem/DesignSystem/Components/CheckBoxButton.swift
  MLS/Presentation/DesignSystem/DesignSystem/Resource/Image.xcassets/logo.imageset/Contents.json
  MLS/Presentation/DesignSystem/DesignSystem/Resource/Image.xcassets/logo.imageset/logo.png
  MLS/Presentation/DesignSystem/DesignSystem/Resource/Image.xcassets/logo.imageset/logo.svg
Labels: feat, fix

#75 에러메세지 구현
  MLS/Presentation/DesignSystem/DesignSystem/Components/ErrorMessage.swift
  MLS/Presentation/DesignSystem/DesignSystem/Components/InputBox.swift
  MLS/Presentation/DesignSystem/DesignSystem/Resource/Image.xcassets/error.imageset/Contents.json
  MLS/Presentation/DesignSystem/DesignSystem/Resource/Image.xcassets/error.imageset/error.svg
  MLS/Presentation/DesignSystem/DesignSystem/Utills/Extension/UIColor+.swift
  MLS/Presentation/DesignSystem/DesignSystemDemo/ComponentsTest/ErrorMessageTextViewController.swift
  MLS/Presentation/DesignSystem/DesignSystemDemo/ViewController.swift
Labels: feat

#78 login화면
  MLS/.DS_Store
  MLS/Presentation/AuthFeature/AuthFeature.xcodeproj/project.pbxproj
  MLS/Presentation/AuthFeature/AuthFeature/Login/LoginFactoryImpl.swift
  MLS/Presentation/AuthFeature/AuthFeature/Login/LoginReactor.swift
  MLS/Presentation/AuthFeature/AuthFeature/Login/LoginView.swift
  MLS/Presentation/AuthFeature/AuthFeature/Login/LoginViewController.swift
  MLS/Presentation/AuthFeature/AuthFeature/TermsAgreement/TermsAgreementFactoryImpl.swift
  MLS/Presentation/AuthFeature/AuthFeature/TermsAgreement/TermsAgreementReactor.swift
  MLS/Presentation/AuthFeature/AuthFeature/TermsAgreement/TermsAgreementView.swift
  MLS/Presentation/AuthFeature/AuthFeature/TermsAgreement/TermsAgreementViewController.swift
  MLS/Presentation/AuthFeature/AuthFeatureDemo/SceneDelegate.swift
  MLS/Presentation/AuthFeature/AuthFeatureInterface/LoginFactory.swift
  MLS/Presentation/AuthFeature/AuthFeatureInterface/TermsAgreementFactory.swift
  MLS/Presentation/BaseFeature/BaseFeature/BaseViewController.swift
  MLS/Presentation/DesignSystem/DesignSystem/Components/CheckBoxButton.swift
  MLS/Presentation/DesignSystem/DesignSystem/Components/CommonButton.swift
  MLS/Presentation/DesignSystem/DesignSystem/Components/ErrorMessage.swift
  MLS/Presentation/DesignSystem/DesignSystem/Components/NavigationBar.swift
  MLS/Presentation/DesignSystem/DesignSystem/Components/Toast.swift
  MLS/Presentation/DesignSystem/DesignSystem/Resource/Image.xcassets/AppleLogo.imageset/AppleLogo.svg
  MLS/Presentation/DesignSystem/DesignSystem/Resource/Image.xcassets/AppleLogo.imageset/Contents.json
  MLS/Presentation/DesignSystem/DesignSystem/Resource/Image.xcassets/Login_KV_img.imageset/Contents.json
  MLS/Presentation/DesignSystem/DesignSystem/Resource/Image.xcassets/Login_KV_img.imageset/Login_KV_img.png
  MLS/Presentation/DesignSystem/DesignSystem/Resource/Image.xcassets/kakaoLogo.imageset/Contents.json
  MLS/Presentation/DesignSystem/DesignSystem/Resource/Image.xcassets/kakaoLogo.imageset/kakaoLogo.svg
  MLS/Presentation/DesignSystem/DesignSystem/Utills/Extension/UIColor+.swift
  MLS/Presentation/DesignSystem/DesignSystem/Utills/Extension/UIFont+.swift
  MLS/Presentation/DesignSystem/DesignSystemDemo/ComponentsTest/CheckBoxButtonTestViewController.swift
  MLS/Presentation/DesignSystem/DesignSystemDemo/ComponentsTest/CommonButtonTestViewController.swift
  MLS/Presentation/DesignSystem/DesignSystemDemo/ComponentsTest/DropDwonBoxTestViewController.swift
  MLS/Presentation/DesignSystem/DesignSystemDemo/ComponentsTest/ErrorMessageTextViewController.swift
  MLS/Presentation/DesignSystem/DesignSystemDemo/ComponentsTest/InputBoxTextViewController.swift
  MLS/Presentation/DesignSystem/DesignSystemDemo/ComponentsTest/NavigationBarTestViewController.swift
  MLS/Presentation/DesignSystem/DesignSystemDemo/ComponentsTest/ToastMakerTestViewController.swift
Labels: feat

#79 logo Image 디자인 수정
  MLS/Presentation/AuthFeature/AuthFeature/TermsAgreement/TermsAgreementView.swift
  MLS/Presentation/DesignSystem/DesignSystem/Resource/Image.xcassets/logo.imageset/Contents.json
  MLS/Presentation/DesignSystem/DesignSystem/Resource/Image.xcassets/logo.imageset/logo.png
  MLS/Presentation/DesignSystem/DesignSystem/Resource/Image.xcassets/logo.imageset/logo.svg
Labels: fix

#80 ToastFactory 추가
  MLS/MLS/Application/AppDelegate.swift
  MLS/Presentation/AuthFeature/AuthFeature.xcodeproj/project.pbxproj
  MLS/Presentation/AuthFeature/AuthFeatureDemo/SceneDelegate.swift
  MLS/Presentation/BaseFeature/BaseFeature.xcodeproj/project.pbxproj
  MLS/Presentation/BaseFeature/BaseFeature/Base/BaseViewController.swift
  MLS/Presentation/BaseFeature/BaseFeature/Utills/ImageLoader/ImageLoader.swift
  MLS/Presentation/BaseFeature/BaseFeature/Utills/ImageLoader/Storage/DiskStorage.swift
  MLS/Presentation/BaseFeature/BaseFeature/Utills/ImageLoader/Storage/MemoryStorage.swift
  MLS/Presentation/BaseFeature/BaseFeature/Utills/ToastFactory.swift
Labels: feat

#81 온보딩 페이지 UI 구현
  MLS/Presentation/AuthFeature/AuthFeature/OnBoarding/CustomNavigationConroller.swift
  MLS/Presentation/AuthFeature/AuthFeature/OnBoarding/Input/OnBoardingInputView.swift
  MLS/Presentation/AuthFeature/AuthFeature/OnBoarding/Input/OnBoardingInputViewController.swift
  MLS/Presentation/AuthFeature/AuthFeature/OnBoarding/Notification/OnBoardingNotificationView.swift
  MLS/Presentation/AuthFeature/AuthFeature/OnBoarding/Notification/OnBoardingNotificationViewController.swift
  MLS/Presentation/AuthFeature/AuthFeature/OnBoarding/Question/OnBoardingQuestionView.swift
  MLS/Presentation/AuthFeature/AuthFeature/OnBoarding/Question/OnBoardingQuestionViewController.swift
  MLS/Presentation/AuthFeature/AuthFeatureDemo/SceneDelegate.swift
  MLS/Presentation/DesignSystem/DesignSystem/Components/DropDownBox.swift
  MLS/Presentation/DesignSystem/DesignSystem/Components/InputBox.swift
  MLS/Presentation/DesignSystem/DesignSystem/Resource/Image.xcassets/img_onBoarding_notification.imageset/Contents.json
  MLS/Presentation/DesignSystem/DesignSystem/Resource/Image.xcassets/img_onBoarding_notification.imageset/img_notification.png
  MLS/Presentation/DesignSystem/DesignSystem/Resource/Image.xcassets/img_onBoarding_question.imageset/Contents.json
  MLS/Presentation/DesignSystem/DesignSystem/Resource/Image.xcassets/img_onBoarding_question.imageset/img_question.png
Labels: feat

#83 ModalPresentable
  MLS/Presentation/BaseFeature/BaseFeature/Utills/ModalPresentable/ModalPresentable.swift
  MLS/Presentation/BaseFeature/BaseFeature/Utills/ModalPresentable/ModalWrapperView.swift
  MLS/Presentation/BaseFeature/BaseFeature/Utills/ModalPresentable/UIViewController+.swift
  MLS/Presentation/DesignSystem/DesignSystem/Utills/Extension/UIColor+.swift
Labels: feat

#85 소셜로그인 유즈케이스 연동 작업
  MLS/Core/Core.xcodeproj/project.pbxproj
  MLS/Core/Core/DIContainer/DIContainer.swift
  MLS/Data/Data.xcodeproj/project.pbxproj
  MLS/Data/Data/Providers/AppleLoginProviderImpl.swift
  MLS/Data/Data/Providers/KakaoLoginProviderImpl.swift
  MLS/Domain/Domain.xcodeproj/project.pbxproj
  MLS/Domain/Domain/SocialLoginUseCaseImpl.swift
  MLS/Domain/Domain/Temp.swift
  MLS/Domain/DomainInterface/Providers/SocialAuthenticatableProvider.swift
  MLS/MLS.xcodeproj/project.pbxproj
  MLS/MLS/Application/AppDelegate.swift
  MLS/MLS/Application/SceneDelegate.swift
  MLS/MLS/MLS.entitlements
  MLS/MLS/Resource/Info.plist
  MLS/Presentation/AuthFeature/AuthFeature.xcodeproj/project.pbxproj
  MLS/Presentation/AuthFeature/AuthFeature/Login/LoginFactoryImpl.swift
  MLS/Presentation/AuthFeature/AuthFeature/Login/LoginReactor.swift
  MLS/Presentation/AuthFeature/AuthFeatureInterface/LoginFactory.swift
  MLS/Presentation/BaseFeature/BaseFeature.xcodeproj/project.pbxproj
  MLS/Presentation/DesignSystem/DesignSystem.xcodeproj/project.pbxproj
Labels: feat, fix
